services:
  # ==================== Auth 认证服务 ====================
  authapi:
    image: registry.cn-shenzhen.aliyuncs.com/tmd/sso:authapi
    container_name: authapi
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
    ports:
      - "7086:80"
    volumes:
      - ./config/certbot/encryption.pfx:/app/certbot/encryption.pfx
      - ./config/certbot/signing.pfx:/app/certbot/signing.pfx
      - ./config/authapi/appsettings.Production.json:/app/appsettings.Production.json:ro
      - ./logs/authapi:/app/logs
    networks:
      - app
      - saas
      - infrastructure

  # ==================== Admin 管理服务 ====================
  adminapi:
    image: registry.cn-shenzhen.aliyuncs.com/tmd/sso:adminapi
    container_name: adminapi
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
    ports:
      - "7089:80"
    volumes:
      - admin_uploads:/app/wwwroot/avatars
      - ./config/adminapi/appsettings.Production.json:/app/appsettings.Production.json:ro
      - ./logs/adminapi:/app/logs
    depends_on:
      - authapi
    networks:
      - app
      - saas
      - infrastructure

  # ==================== 认证前端（tpssoauth）====================
  authweb:
    image: registry.cn-shenzhen.aliyuncs.com/tmd/sso:authweb
    container_name: authweb
    restart: unless-stopped
    ports:
      - "7087:80"
    depends_on:
      - authapi
    networks:
      - app
      - saas
      - infrastructure

  # ==================== 管理后台前端（tpssoadmin）====================
  adminweb:
    image: registry.cn-shenzhen.aliyuncs.com/tmd/sso:adminweb
    container_name: adminweb
    restart: unless-stopped
    ports:
      - "7088:80"
    depends_on:
      - adminapi
    networks:
      - app
      - saas
      - infrastructure
  cloudflared_sso:
    container_name: cloudflared_sso
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN_SSO}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN_SSO}
    restart: unless-stopped
    networks:
      - infrastructure
      - saas
      - app
# ==================== 数据卷 ====================
volumes:
  admin_uploads:
    driver: local

# ==================== 网络 ====================
networks:
  infrastructure:
    external: true
  saas:
    external: true
  app:
    external: true